name: PHPStan

on:
  pull_request:

jobs:
  phpstan:
    uses: icinga/github-actions/.github/workflows/phpstan.yml@main
    with:
      phpExtensions: ldap
      dependencies: |
        {
          "/icingaweb2"                             : "https://github.com/Icinga/icingaweb2.git",
          "/usr/share/icingaweb2-modules/x509"      : "https://github.com/Icinga/icingaweb2-module-x509.git",
          "/usr/share/icingaweb2-modules/pdfexport" : "https://github.com/Icinga/icingaweb2-module-pdfexport.git",
          "/usr/share/icingaweb2-modules/reporting" : "https://github.com/Icinga/icingaweb2-module-reporting.git"
        }
